const LIBRARY_BATCH3 = [
 // GPC CHAIN
 {id:'enterococcus_faecium',group:'gpc_chain',name:'Enterococcus faecium',thai:'เอนเทอโรค็อกคัส ฟีเชียม',gram:'+',morph:'Cocci in pairs/short chains',
  importance:'high',tags:['6.5%NaCl+','Bile Esculin+','PYR+','VRE risk','Sorbitol−'],
  clinical:{habitat:'GI tract normal flora',diseases:['UTI (nosocomial)','Bacteremia','Endocarditis'],transmission:'Endogenous; healthcare settings',factors:'High rate of VRE (Vancomycin-Resistant Enterococcus) compared to E. faecalis'},
  colony:{BAP:'Small, γ or α-hemolysis, grey-white'},
  gramStain:'GPC pairs/short chains',
  biochem:[{t:'Catalase',r:'−',n:''},{t:'6.5% NaCl',r:'+',n:''},{t:'Bile Esculin',r:'+',n:''},{t:'PYR',r:'+',n:''},{t:'Growth 45°C',r:'+',n:''},{t:'Sorbitol',r:'−',n:'KEY vs E. faecalis (+)'},{t:'Arabinose',r:'+',n:'KEY vs E. faecalis (−)'}],
  media:['Blood agar','Bile Esculin agar'],condition:'37°C aerobic/anaerobic',
  notes:'Sorbitol− and Arabinose+ ช่วยแยกออกจาก E. faecalis; มีอัตราการดื้อยา VRE ที่สูงมาก'},

 // GPB
 {id:'erysipelothrix_rhusiopathiae',group:'gpb',name:'Erysipelothrix rhusiopathiae',thai:'อีริซิพีโลทริกซ์ รูซิโอพาเทีย',gram:'+',morph:'Pleomorphic rods',
  importance:'moderate',tags:['Bottle brush','H₂S+','Zoonotic','Erysipeloid','Non-motile'],
  clinical:{habitat:'Ubiquitous, animals (pigs, fish, birds)',diseases:['Erysipeloid (localized skin infection)','Septicemia','Endocarditis (rare)'],transmission:'Direct contact with infected animals/meat (occupational: butchers, fishermen)',factors:'Neuraminidase; capsule'},
  colony:{BAP:'Small, round, transparent, α-hemolysis'},
  gramStain:'GPB short rods to long filaments (gram variable easily)',
  biochem:[{t:'Catalase',r:'−',n:'KEY vs Listeria (+)'},{t:'Motile',r:'−',n:'KEY vs Listeria (+)'},{t:'H₂S in TSI',r:'+',n:'KEY: Only GPB that produces H₂S!'},{t:'Glucose',r:'+',n:''},{t:'Maltose',r:'V',n:''},{t:'Sucrose',r:'−',n:''},{t:'Xylose',r:'−',n:''},{t:'Esculin',r:'−',n:''},{t:'Urease',r:'−',n:''}],
  media:['Blood agar'],condition:'37°C aerobic',
  notes:'Only GPB that is H₂S positive on TSI! Typical bottle-brush growth in gelatin. Non-motile helps distinguish from Listeria.'},
 {id:'gardnerella_vaginalis',group:'gpb',name:'Gardnerella vaginalis',thai:'การ์ดเนอเรลลา วาจินาลิส',gram:'+',morph:'Pleomorphic rods',
  importance:'moderate',tags:['Clue cells','Bacterial vaginosis','Whiff test'],
  clinical:{habitat:'Human urogenital tract',diseases:['Bacterial vaginosis (BV)'],transmission:'Endogenous imbalance of flora',factors:'Biofilm'},
  colony:{BAP:'Pinpoint, β-hemolysis on human/rabbit blood but NOT sheep blood'},
  gramStain:'Gram-variable pleomorphic coccobacilli',
  biochem:[{t:'Catalase',r:'−',n:''},{t:'Motile',r:'−',n:''},{t:'H₂S in TSI',r:'−',n:''},{t:'Glucose',r:'+',n:''},{t:'Maltose',r:'V',n:''},{t:'Sucrose',r:'V',n:''},{t:'Esculin',r:'−',n:''}],
  media:['V agar (human blood agar)'],condition:'37°C CO2, H2O2 inhibition',
  notes:'Clue cells on wet mount. Positive Whiff test (fishy odor with 10% KOH). Gram variable.'},
 {id:'arcanobacterium_haemolyticum',group:'gpb',name:'Arcanobacterium haemolyticum',thai:'อาร์คาโนแบคทีเรียม ฮีโมลิติคัม',gram:'+',morph:'Pleomorphic rods',
  importance:'moderate',tags:['Reverse CAMP+','β-hemolysis','Pharyngitis'],
  clinical:{habitat:'Human pharynx/skin',diseases:['Pharyngitis/tonsillitis (especially in young adults)','Skin infections'],transmission:'Person to person',factors:'Phospholipase D'},
  colony:{BAP:'Small, β-hemolysis (often mistaken for GAS)'},
  gramStain:'Pleomorphic GP rods (may show branching)',
  biochem:[{t:'Catalase',r:'−',n:''},{t:'Motile',r:'−',n:''},{t:'CAMP test',r:'Reverse CAMP+',n:'Inhibits S. aureus beta-lysin!'},{t:'Glucose',r:'+',n:''},{t:'Maltose',r:'V',n:''},{t:'Sucrose',r:'−',n:''}],
  media:['Blood agar'],condition:'37°C aerobic/CO2',
  notes:'Reverse CAMP test positive (arrow shape pointing away from S. aureus). Causes pharyngitis resembling Strep pyogenes.'},

 // NFB
 {id:'stenotrophomonas_maltophilia',group:'nfb',name:'Stenotrophomonas maltophilia',thai:'สเตโนโทรโฟโมแนส มัลโทฟิเลีย',gram:'−',morph:'Rods',
  importance:'high',tags:['Oxidase−','DNase+','Maltose+','Nosocomial','SXT sensitive'],
  clinical:{habitat:'Water, soil, plants, hospital environments',diseases:['HAP/VAP','Bacteremia','UTI (catheter)'],transmission:'Nosocomial',factors:'Biofilm, resistance to carbapenems (intrinsic L1/L2 metallo-beta-lactamases)'},
  colony:{BAP:'Large, pale yellow/lavender green, ammonia odor',MAC:'NLF'},
  gramStain:'GN short rods, motile (polar tuft flagella)',
  biochem:[{t:'Oxidase',r:'−',n:'KEY vs Pseudomonas (+)'},{t:'TSI',r:'K/K or K/N',n:''},{t:'Motile',r:'+',n:''},{t:'DNase',r:'+',n:'KEY test'},{t:'Glucose O/F',r:'O',n:'Weak oxidizer'},{t:'Maltose',r:'+',n:'Strong oxidizer (hence maltophilia)'},{t:'Esculin',r:'+',n:''},{t:'Urease',r:'−',n:''},{t:'Nitrate reduction',r:'V',n:''}],
  media:['Blood agar','MacConkey'],condition:'37°C aerobic',
  notes:'Oxidase negative NFB + DNase positive + Maltose oxidizer = S. maltophilia. Intrinsically resistant to Imipenem, treatment of choice is TMP-SMX.'},
 {id:'pseudomonas_fluorescens',group:'nfb',name:'Pseudomonas fluorescens',thai:'ซูโดโมแนส ฟลูออเรสเซนส์',gram:'−',morph:'Rods',
  importance:'moderate',tags:['King F+','Pyoverdin','No growth 42°C','Gelatin+'],
  clinical:{habitat:'Environmental, water, soil, refrigerated foods',diseases:['Transfusion-associated bacteremia (grows at 4°C)','Rarely opportunistic'],transmission:'Contaminated medical devices/blood products',factors:'Cold growth'},
  colony:{BAP:'Grey, mucoid, fluorescent yellow-green under UV'},
  gramStain:'GNB motile',
  biochem:[{t:'Oxidase',r:'+',n:''},{t:'King F',r:'+',n:'Fluorescein+'},{t:'King P',r:'−',n:'Pyocyanin negative'},{t:'Growth at 42°C',r:'−',n:'KEY vs P. aeruginosa (+)'},{t:'Gelatin',r:'+',n:'KEY vs P. putida (−)'},{t:'Nitrate reduction',r:'+',n:''},{t:'N₂ gas from NO₃',r:'−',n:'vs P. aeruginosa'}],
  media:['Blood agar','MacConkey','King B'],condition:'Grows well at 25-30°C, does NOT grow at 42°C',
  notes:'Produces pyoverdin (fluorescein) but NOT pyocyanin. Can grow at 4°C.'},
 {id:'pseudomonas_putida',group:'nfb',name:'Pseudomonas putida',thai:'ซูโดโมแนส พูทิดา',gram:'−',morph:'Rods',
  importance:'low',tags:['King F+','No growth 42°C','Gelatin−'],
  clinical:{habitat:'Environmental, water, soil',diseases:['Rare opportunistic (catheter-related bacteremia)'],transmission:'Nosocomial/water',factors:'Low virulence'},
  colony:{BAP:'Grey, fluorescent'},
  gramStain:'GNB motile',
  biochem:[{t:'Oxidase',r:'+',n:''},{t:'King F',r:'+',n:''},{t:'King P',r:'−',n:''},{t:'Growth at 42°C',r:'−',n:''},{t:'Gelatin',r:'−',n:'KEY vs P. fluorescens (+)'}],
  media:['Blood agar','MacConkey'],condition:'25-30°C',
  notes:'Similar to P. fluorescens but is Gelatin hydrolysis negative.'},
 {id:'pseudomonas_stutzeri',group:'nfb',name:'Pseudomonas stutzeri',thai:'ซูโดโมแนส สตุทเซอรี',gram:'−',morph:'Rods',
  importance:'moderate',tags:['Wrinkled colony','Starch+','N₂ gas+'],
  clinical:{habitat:'Soil, water, hospital equipment',diseases:['Opportunistic wound, UTI, bacteremia'],transmission:'Environmental exposure',factors:'None specific'},
  colony:{BAP:'Dry, wrinkled, leathery, adherent! (Can look like B. pseudomallei)'},
  gramStain:'GNB motile',
  biochem:[{t:'Oxidase',r:'+',n:''},{t:'N₂ gas from NO₃',r:'+',n:''},{t:'Starch',r:'+',n:'KEY test for P. stutzeri'},{t:'Growth at 42°C',r:'+',n:''}],
  media:['Blood agar','MacConkey'],condition:'37°C aerobic',
  notes:'Wrinkled colonies + Starch hydrolysis positive = P. stutzeri.'},
 {id:'burkholderia_cepacia',group:'nfb',name:'Burkholderia cepacia complex',thai:'เบิร์คโฮลเดอเรีย เซปาเชีย',gram:'−',morph:'Rods',
  importance:'high',tags:['CF patient','BCSA','LDC+','ODC−'],
  clinical:{habitat:'Soil, water, hospital equipment/fluids (even disinfectants!)',diseases:['Pneumonia in Cystic Fibrosis (CF) patients (Cepacia syndrome)','Bacteremia'],transmission:'Nosocomial; contaminated equipment/solutions',factors:'High intrinsic resistance'},
  colony:{BAP:'Smooth, sometimes yellow/green pigment',BCSA:'Yellow halo (sucrose/lactose oxidizer)'},
  gramStain:'GNB, polar tuft motile',
  biochem:[{t:'Oxidase',r:'+ (weak)',n:''},{t:'LDC',r:'+',n:'KEY vs S. maltophilia (−)'},{t:'ODC',r:'−',n:''},{t:'Sucrose',r:'+',n:''},{t:'DNase',r:'−',n:'vs S. maltophilia'}],
  media:['BCSA (B. cepacia selective agar)','Blood agar','MacConkey'],condition:'37°C aerobic',
  notes:'Major pathogen for CF patients. Intrinsically MDR, use TMP-SMX or meropenem.'},
 {id:'burkholderia_thailandensis',group:'nfb',name:'Burkholderia thailandensis',thai:'เบิร์คโฮลเดอเรีย ไทยแลนเดนซิส',gram:'−',morph:'Rods',
  importance:'low',tags:['Arabinose+','Melioidosis mimic','Non-pathogenic'],
  clinical:{habitat:'Soil and water in SE Asia',diseases:['Rarely causes disease in humans'],transmission:'Environmental',factors:'Lacks key virulence factors of B. pseudomallei'},
  colony:{BAP:'Similar to B. pseudomallei'},
  gramStain:'GNB bipolar staining',
  biochem:[{t:'Oxidase',r:'+',n:''},{t:'Arabinose',r:'+',n:'KEY differentiator from B. pseudomallei (−)'},{t:'Growth 42°C',r:'−',n:''}],
  media:['Ashdown agar'],condition:'37°C',
  notes:'Environmental mimic of B. pseudomallei, but Arabinose positive!'},
 {id:'shewanella_putrefaciens',group:'nfb',name:'Shewanella putrefaciens',thai:'ชีวาเนลลา พิวทรีเฟเชียนส์',gram:'−',morph:'Rods',
  importance:'moderate',tags:['H₂S+ (NFB)','Oxidase+','Marine'],
  clinical:{habitat:'Marine environments, fish',diseases:['Wound infections (seawater exposure)','Otitis media'],transmission:'Seawater',factors:'Halophilic'},
  colony:{BAP:'Orange/tan pigment, convex'},
  gramStain:'GN straight or curved rods',
  biochem:[{t:'Oxidase',r:'+',n:''},{t:'H₂S in TSI',r:'+',n:'KEY: Only prominent NFB that is H₂S positive!'},{t:'Motile',r:'+',n:''},{t:'Glucose O/F',r:'−/−',n:'Non-saccharolytic (or weak)'},{t:'6.5% NaCl',r:'−',n:'(S. algae is +)'}],
  media:['Blood agar','MacConkey'],condition:'37°C',
  notes:'H₂S production + NFB + Oxidase+ = Shewanella. (S. algae is halophilic and grows in 6.5% NaCl)'},
 {id:'shewanella_algae',group:'nfb',name:'Shewanella algae',thai:'ชีวาเนลลา แอลเจ',gram:'−',morph:'Rods',
  importance:'moderate',tags:['H₂S+ (NFB)','Oxidase+','Halophilic'],
  clinical:{habitat:'Marine environments, seawater',diseases:['Wound infections, bacteremia'],transmission:'Seawater exposure',factors:'More virulent than S. putrefaciens'},
  colony:{BAP:'Mucoid, beta-hemolysis'},
  gramStain:'GNB',
  biochem:[{t:'Oxidase',r:'+',n:''},{t:'H₂S in TSI',r:'+',n:''},{t:'Motile',r:'+',n:''},{t:'6.5% NaCl',r:'+',n:'KEY vs S. putrefaciens (−)'}],
  media:['Blood agar'],condition:'37°C',
  notes:'True human pathogen compared to S. putrefaciens. Halotolerant (requires/tolerates NaCl).'},
 {id:'elizabethkingia_meningoseptica',group:'nfb',name:'Elizabethkingia meningoseptica',thai:'อลิซาเบธคิงเจีย เมนิงโกเซปติกา',gram:'−',morph:'Rods (thin)',
  importance:'high',tags:['Neonatal meningitis','Pale yellow pigment','Indole+','Non-motile'],
  clinical:{habitat:'Hospital water systems, soil',diseases:['Neonatal meningitis (high mortality)','Pneumonia/bacteremia in ICU'],transmission:'Nosocomial water sources',factors:'MDR'},
  colony:{BAP:'Pale yellow pigment, smooth',MAC:'Poor or no growth!'},
  gramStain:'Thin GN bacilli',
  biochem:[{t:'Oxidase',r:'+',n:''},{t:'Motile',r:'−',n:'KEY'},{t:'Indole',r:'+',n:'KEY (one of the few NFB Indole+)'},{t:'DNase',r:'+',n:''},{t:'Esculin',r:'+',n:''},{t:'Mannitol',r:'+',n:''}],
  media:['Blood agar'],condition:'37°C',
  notes:'Yellow pigment + Indole+ + Non-motile + Oxidase+ = Elizabethkingia. Huge MDR problem.'},
 {id:'acinetobacter_lwoffii',group:'nfb',name:'Acinetobacter lwoffii',thai:'อาซิเนโตแบคเตอร์ ลวอฟฟิไอ',gram:'−',morph:'Coccobacilli',
  importance:'low',tags:['Oxidase−','Asaccharolytic','Non-motile'],
  clinical:{habitat:'Skin flora, hospital environment',diseases:['Opportunistic, catheter-related bacteremia'],transmission:'Nosocomial',factors:'Less virulent than A. baumannii'},
  colony:{BAP:'Small, white-grey',MAC:'NLF'},
  gramStain:'GN coccobacilli',
  biochem:[{t:'Oxidase',r:'−',n:''},{t:'Motile',r:'−',n:''},{t:'Glucose O/F',r:'−/−',n:'KEY vs A. baumannii (O/F +/−)'},{t:'Lactose',r:'−',n:''}],
  media:['Blood agar','MacConkey'],condition:'37°C',
  notes:'Asaccharolytic Acinetobacter (does not use glucose) unlike A. baumannii.'},

 // ENTEROBACTERALES
 {id:'citrobacter_freundii',group:'enterobacterales',name:'Citrobacter freundii',thai:'ซิทรูแบคเตอร์ ฟรอยเดีย',gram:'−',morph:'Rods',
  importance:'moderate',tags:['H₂S+','LDC−','Urease slow','LF'],
  clinical:{habitat:'GI flora, water, soil',diseases:['UTI','RTI','Bacteremia'],transmission:'Endogenous/environmental',factors:'Some produce Shiga-like toxin, AmpC'},
  colony:{BAP:'Grey, dome',MAC:'LF (pink) - late'},
  gramStain:'GNB',
  biochem:[{t:'TSI',r:'A/AG H₂S',n:'Looks like Salmonella!'},{t:'H₂S',r:'+',n:''},{t:'Indole',r:'−',n:''},{t:'MR',r:'+',n:''},{t:'VP',r:'−',n:''},{t:'Citrate',r:'+',n:''},{t:'Motility',r:'+',n:''},{t:'Urease',r:'+ (slow)',n:''},{t:'LDC',r:'−',n:'KEY vs Salmonella (+)'},{t:'ODC',r:'−',n:''},{t:'Malonate',r:'−',n:''},{t:'Adonitol',r:'−',n:''}],
  media:['Blood agar','MacConkey'],condition:'37°C',
  notes:'Looks like Salmonella on TSI (H₂S+) but is LDC negative and LF (late).'},
 {id:'citrobacter_koseri',group:'enterobacterales',name:'Citrobacter koseri (diversus)',thai:'ซิทรูแบคเตอร์ โคเซอรี',gram:'−',morph:'Rods',
  importance:'moderate',tags:['H₂S−','Indole+','Adonitol+','Neonatal meningitis'],
  clinical:{habitat:'GI flora',diseases:['Neonatal meningitis (brain abscesses!)','UTI'],transmission:'Vertical, nosocomial',factors:'Neurotropism'},
  colony:{BAP:'Grey',MAC:'NLF or LF'},
  gramStain:'GNB',
  biochem:[{t:'TSI',r:'A/AG',n:'No H2S'},{t:'Indole',r:'+',n:'KEY vs C. freundii'},{t:'MR',r:'+',n:''},{t:'VP',r:'−',n:''},{t:'Citrate',r:'+',n:''},{t:'Malonate',r:'+',n:''},{t:'Adonitol',r:'+',n:'KEY'},{t:'LDC',r:'−',n:''},{t:'ODC',r:'+',n:''}],
  media:['MacConkey'],condition:'37°C',
  notes:'Indole+ and Adonitol+ differentiates from C. freundii. Known for causing brain abscesses in neonates.'},
 {id:'citrobacter_amalonaticus',group:'enterobacterales',name:'Citrobacter amalonaticus',thai:'ซิทรูแบคเตอร์ อะมาโลนาติคัส',gram:'−',morph:'Rods',
  importance:'low',tags:['Indole+','Malonate−'],
  clinical:{habitat:'GI flora',diseases:['UTI'],transmission:'Endogenous',factors:'Similar to other Citrobacter'},
  colony:{BAP:'Grey',MAC:'LF or NLF'},
  gramStain:'GNB',
  biochem:[{t:'TSI',r:'A/AG',n:''},{t:'Indole',r:'+',n:''},{t:'Malonate',r:'−',n:'KEY vs C. koseri (+)'},{t:'Adonitol',r:'−',n:''}],
  media:['MacConkey'],condition:'37°C',
  notes:'Similar to C. koseri but is Malonate and Adonitol negative.'},
 {id:'enterobacter_cloacae',group:'enterobacterales',name:'Enterobacter cloacae',thai:'เอนเทอโรแบคเตอร์ คลอเอซี',gram:'−',morph:'Rods',
  importance:'high',tags:['VP+','LDC−','ODC+','AmpC','LF'],
  clinical:{habitat:'GI flora, hospital environment',diseases:['Nosocomial pneumonia','UTI','Wound'],transmission:'Nosocomial',factors:'AmpC cephalosporinase'},
  colony:{BAP:'Large, grey, mucoid',MAC:'LF (pink), mucoid'},
  gramStain:'GNB',
  biochem:[{t:'TSI',r:'A/AG',n:''},{t:'Indole',r:'−',n:''},{t:'MR',r:'−',n:''},{t:'VP',r:'+',n:''},{t:'Citrate',r:'+',n:''},{t:'Motility',r:'+',n:''},{t:'Urease',r:'+',n:''},{t:'LDC',r:'−',n:'KEY vs K. aerogenes (+)'},{t:'ODC',r:'+',n:'KEY vs Klebsiella (−)'},{t:'Malonate',r:'+',n:''}],
  media:['MacConkey'],condition:'37°C',
  notes:'LDC negative / ODC positive differentiates E. cloacae from K. aerogenes.'},
 {id:'enterobacter_agglomerans',group:'enterobacterales',name:'Pantoea (Enterobacter) agglomerans',thai:'แพนโทเอีย อักโกลเมอแรนส์',gram:'−',morph:'Rods',
  importance:'moderate',tags:['Plant pathogen','Yellow pigment','Triple decarb−'],
  clinical:{habitat:'Plants, soil',diseases:['Thorn prick wound infections','Septicemia'],transmission:'Thorn punctures',factors:'Environmental'},
  colony:{BAP:'Yellow pigment (often)',MAC:'LF or NLF'},
  gramStain:'GNB',
  biochem:[{t:'TSI',r:'A/A',n:''},{t:'Indole',r:'−',n:''},{t:'VP',r:'+',n:''},{t:'LDC',r:'−',n:''},{t:'ODC',r:'−',n:''},{t:'Malonate',r:'+/−',n:''}],
  media:['MacConkey'],condition:'37°C',
  notes:'Associated with plant thorn injuries. Triple decarboxylase negative usually.'},
 {id:'klebsiella_aerogenes',group:'enterobacterales',name:'Klebsiella (Enterobacter) aerogenes',thai:'เคล็บเซียลลา แอโรจิเนส',gram:'−',morph:'Rods',
  importance:'high',tags:['VP+','LDC+','ODC+','LF'],
  clinical:{habitat:'Environment, GI tract',diseases:['Nosocomial infections'],transmission:'Nosocomial',factors:'Capsule, AmpC'},
  colony:{BAP:'Grey, mucoid',MAC:'LF (pink)'},
  gramStain:'GNB',
  biochem:[{t:'TSI',r:'A/AG',n:''},{t:'Indole',r:'−',n:''},{t:'VP',r:'+',n:''},{t:'LDC',r:'+',n:'KEY vs E. cloacae (−)'},{t:'ODC',r:'+',n:''},{t:'Malonate',r:'+',n:''},{t:'Adonitol',r:'+',n:''}],
  media:['MacConkey'],condition:'37°C',
  notes:'Formerly Enterobacter aerogenes. LDC positive distinguishes it from E. cloacae.'},
 {id:'klebsiella_oxytoca',group:'enterobacterales',name:'Klebsiella oxytoca',thai:'เคล็บเซียลลา ออกซิโทคา',gram:'−',morph:'Rods',
  importance:'high',tags:['Indole+','VP+','Non-motile','LF'],
  clinical:{habitat:'GI tract, environment',diseases:['Antibiotic-associated hemorrhagic colitis','Nosocomial pneumonia/UTI'],transmission:'Nosocomial',factors:'Cytotoxin (colitis)'},
  colony:{BAP:'Mucoid, grey',MAC:'LF (pink) mucoid'},
  gramStain:'GNB thick capsule',
  biochem:[{t:'TSI',r:'A/AG',n:''},{t:'Indole',r:'+',n:'KEY vs K. pneumoniae (−)'},{t:'VP',r:'+',n:''},{t:'Urease',r:'+',n:''},{t:'Motility',r:'−',n:'KEY Klebsiella'},{t:'Malonate',r:'+',n:''}],
  media:['MacConkey'],condition:'37°C',
  notes:'Differs from K. pneumoniae primarily by being Indole positive.'},
 {id:'klebsiella_ozaenae',group:'enterobacterales',name:'Klebsiella ozaenae',thai:'เคล็บเซียลลา โอซีเน',gram:'−',morph:'Rods',
  importance:'low',tags:['Ozena','Atrophic rhinitis','MR+','VP−'],
  clinical:{habitat:'Upper respiratory tract',diseases:['Ozena (chronic atrophic rhinitis)'],transmission:'Respiratory',factors:'Capsule'},
  colony:{BAP:'Mucoid',MAC:'NLF or LF'},
  gramStain:'GNB',
  biochem:[{t:'TSI',r:'K/A or A/A',n:''},{t:'Indole',r:'−',n:''},{t:'MR',r:'+',n:'KEY' },{t:'VP',r:'−',n:'KEY (K. pneu is VP+)'},{t:'Urease',r:'−',n:''},{t:'Motility',r:'−',n:''}],
  media:['MacConkey'],condition:'37°C',
  notes:'Classic cause of Ozena. Atypical Klebsiella: MR+ and VP− and Urease−.'},
 {id:'cronobacter_sakazakii',group:'enterobacterales',name:'Cronobacter sakazakii',thai:'โครโนแบคเตอร์ ซากาซากิอิ',gram:'−',morph:'Rods',
  importance:'high',tags:['Infant formula','Neonatal meningitis','Yellow pigment'],
  clinical:{habitat:'Environment, powdered infant formula',diseases:['Severe neonatal meningitis, sepsis, necrotizing enterocolitis'],transmission:'Contaminated formula',factors:'Survival in dry environments'},
  colony:{BAP:'Yellow pigment',MAC:'LF or NLF'},
  gramStain:'GNB',
  biochem:[{t:'TSI',r:'A/AG',n:''},{t:'Indole',r:'−',n:''},{t:'VP',r:'+',n:''},{t:'Motility',r:'+',n:''},{t:'Malonate',r:'−',n:''},{t:'ODC',r:'+',n:''}],
  media:['MacConkey'],condition:'37°C',
  notes:'Major risk for neonates from powdered infant formula. Yellow pigment.'},
 {id:'serratia_rubidaea',group:'enterobacterales',name:'Serratia rubidaea',thai:'เซอราเชีย รูบิเดีย',gram:'−',morph:'Rods',
  importance:'low',tags:['Red pigment','Adonitol+','Arabinose+'],
  clinical:{habitat:'Environment',diseases:['Rare opportunistic'],transmission:'Nosocomial',factors:'Prodigiosin'},
  colony:{BAP:'Red/Pink pigment',MAC:'NLF/LF'},
  gramStain:'GNB',
  biochem:[{t:'TSI',r:'A/A',n:''},{t:'Indole',r:'−',n:''},{t:'VP',r:'+',n:''},{t:'DNase',r:'+',n:''},{t:'Arabinose',r:'+',n:'KEY vs S. marcescens (−)'},{t:'Adonitol',r:'+',n:'KEY vs S. marcescens (−)'}],
  media:['MacConkey'],condition:'37°C',
  notes:'Similar to S. marcescens but Arabinose positive and Adonitol positive.'},

 // PROTEAE (Morganella, Providencia, Proteus) & OTHERS
 {id:'morganella_morganii',group:'enterobacterales',name:'Morganella morganii',thai:'มอร์กาเนลลา มอร์กานี',gram:'−',morph:'Rods',
  importance:'moderate',tags:['PDC+','Urease+','NLF','ODC+','H₂S−'],
  clinical:{habitat:'GI flora',diseases:['UTI (CAUTI)','Wound infections'],transmission:'Nosocomial',factors:'Urease'},
  colony:{BAP:'Grey. NO swarming!',MAC:'NLF'},
  gramStain:'GNB',
  biochem:[{t:'TSI',r:'K/A or K/AG',n:'No H2S!'},{t:'Indole',r:'+',n:''},{t:'Urease',r:'+',n:''},{t:'Motility',r:'+',n:''},{t:'ODC',r:'+',n:'KEY vs Providencia (−)'},{t:'PDC',r:'+',n:'PD Group'},{t:'H₂S',r:'−',n:'KEY vs Proteus'}],
  media:['MacConkey'],condition:'37°C',
  notes:'Part of the PD positive group. Distinguished by ODC+ and no swarming.'},
 {id:'providencia_rettgeri',group:'enterobacterales',name:'Providencia rettgeri',thai:'โพรวิเดนเซีย เรตเกอรี',gram:'−',morph:'Rods',
  importance:'moderate',tags:['PDC+','Urease+','NLF','Adonitol+'],
  clinical:{habitat:'Environment, GI tract',diseases:['Travelers diarrhea','UTI'],transmission:'Nosocomial',factors:'Urease'},
  colony:{BAP:'Grey',MAC:'NLF'},
  gramStain:'GNB',
  biochem:[{t:'TSI',r:'K/A',n:''},{t:'Indole',r:'+',n:''},{t:'Urease',r:'+',n:'KEY vs P. stuartii (−)'},{t:'ODC',r:'−',n:''},{t:'PDC',r:'+',n:''},{t:'Adonitol',r:'+',n:''}],
  media:['MacConkey'],condition:'37°C',
  notes:'PDC+, Urease+ separates P. rettgeri from P. stuartii (Urease-).'},
 {id:'providencia_stuartii',group:'enterobacterales',name:'Providencia stuartii',thai:'โพรวิเดนเซีย สจวร์ตทิไอ',gram:'−',morph:'Rods',
  importance:'moderate',tags:['PDC+','Urease−','NLF'],
  clinical:{habitat:'Environment',diseases:['UTI (catheter)'],transmission:'Nosocomial',factors:'MDR'},
  colony:{BAP:'Grey',MAC:'NLF'},
  gramStain:'GNB',
  biochem:[{t:'TSI',r:'K/A',n:''},{t:'Indole',r:'+',n:''},{t:'Urease',r:'−',n:'KEY vs P. rettgeri (+)'},{t:'ODC',r:'−',n:''},{t:'PDC',r:'+',n:''}],
  media:['MacConkey'],condition:'37°C',
  notes:'Urease negative.'},
 {id:'proteus_vulgaris',group:'enterobacterales',name:'Proteus vulgaris',thai:'โปรทีอัส วัลการิส',gram:'−',morph:'Rods',
  importance:'moderate',tags:['Swarming','Indole+','H₂S+','PDC+'],
  clinical:{habitat:'GI flora, environment',diseases:['UTI','Wound'],transmission:'Endogenous',factors:'Urease'},
  colony:{BAP:'Swarming!!!',MAC:'NLF'},
  gramStain:'GNB',
  biochem:[{t:'TSI',r:'A/A H₂S or K/A H₂S',n:''},{t:'H₂S',r:'+',n:''},{t:'Indole',r:'+',n:'KEY vs P. mirabilis (−)'},{t:'Urease',r:'++ rapid',n:''},{t:'PDC',r:'+',n:''},{t:'ODC',r:'−',n:'KEY vs P. mirabilis (+)'}],
  media:['Blood agar','MacConkey'],condition:'37°C',
  notes:'Indole positive and ODC negative, which distinguishes it from P. mirabilis.'},
 {id:'proteus_penneri',group:'enterobacterales',name:'Proteus penneri',thai:'โปรทีอัส เพนเนอรี',gram:'−',morph:'Rods',
  importance:'low',tags:['Swarming','Indole−','H₂S+'],
  clinical:{habitat:'Environment',diseases:['UTI'],transmission:'Nosocomial',factors:'Urease'},
  colony:{BAP:'Swarming',MAC:'NLF'},
  gramStain:'GNB',
  biochem:[{t:'TSI',r:'K/A H₂S',n:''},{t:'H₂S',r:'+',n:''},{t:'Indole',r:'−',n:''},{t:'Urease',r:'+',n:''},{t:'PDC',r:'+',n:''},{t:'Maltose',r:'+',n:''}],
  media:['Blood agar'],condition:'37°C',
  notes:'Swarming Proteus that is Indole negative (like mirabilis) but Maltose positive.'},
 {id:'edwardsiella_tarda',group:'enterobacterales',name:'Edwardsiella tarda',thai:'เอดเวิร์ดซีเอลลา ทาร์ดา',gram:'−',morph:'Rods',
  importance:'low',tags:['H₂S+','Indole+','Reptiles/Fish'],
  clinical:{habitat:'Reptiles, turtles, fish, frogs',diseases:['Gastroenteritis','Wound infection (puncture)'],transmission:'Contact with reptiles/fish',factors:'Invades epithelial cells'},
  colony:{BAP:'Grey',MAC:'NLF'},
  gramStain:'GNB',
  biochem:[{t:'TSI',r:'K/A H₂S',n:'Looks like Salmonella'},{t:'H₂S',r:'+',n:''},{t:'Indole',r:'+',n:'KEY vs Salmonella (−)'},{t:'LDC',r:'+',n:''},{t:'Mannitol',r:'−',n:'KEY vs Salmonella (+)'}],
  media:['XLD','SS agar'],condition:'37°C',
  notes:'Associated with reptiles. Very similar to Salmonella biochemically but is Indole positive and Mannitol negative.'},
 {id:'plesiomonas_shigelloides',group:'enterobacterales',name:'Plesiomonas shigelloides',thai:'เพลซิโอโมแนส ชิเกลลอยดีส',gram:'−',morph:'Rods',
  importance:'moderate',tags:['Oxidase+','Enterobacterales','LDC+ ODC+ AD+'],
  clinical:{habitat:'Freshwater, aquatic animals',diseases:['Secretory diarrhea','Bacteremia'],transmission:'Ingestion of contaminated water/seafood',factors:'Enterotoxins'},
  colony:{BAP:'Grey, shiny',MAC:'NLF or late LF'},
  gramStain:'GNB',
  biochem:[{t:'Oxidase',r:'+',n:'KEY: Only Enterobacterales that is Oxidase positive!'},{t:'TSI',r:'K/A',n:''},{t:'Indole',r:'+',n:''},{t:'LDC',r:'+',n:''},{t:'ODC',r:'+',n:''},{t:'ADC (Arginine)',r:'+',n:'Triple decarboxylase positive!'}],
  media:['Blood agar','MacConkey'],condition:'37°C',
  notes:'Recently moved to Enterobacterales family. ONLY Enterobacterales that is Oxidase positive! Triple positive for LDC, ODC, AD.'},
 {id:'yersinia_enterocolitica',group:'enterobacterales',name:'Yersinia enterocolitica',thai:'เยอร์ซินเยีย เอนเทอโรโคไลติกา',gram:'−',morph:'Rods',
  importance:'high',tags:['CIN agar (Bullseye)','Motile@25°C','Pigs','Pseudoappendicitis'],
  clinical:{habitat:'Pigs, domestic animals, refrigerated food',diseases:['Mesenteric lymphadenitis (mimics appendicitis)','Enterocolitis','Transfusion sepsis'],transmission:'Pork (chitterlings), contaminated milk/water',factors:'YOPs (T3SS), grows at 4°C'},
  colony:{BAP:'Small grey',MAC:'NLF',CIN:'Pink center with clear periphery (Bull\'s eye)'},
  gramStain:'GNB, bipolar staining (safety pin)',
  biochem:[{t:'TSI',r:'A/A',n:'Sucrose+ (yellow slant)'},{t:'Indole',r:'V',n:''},{t:'Urease',r:'+',n:''},{t:'Motility',r:'+',n:'Motile at 25°C but NOT at 37°C!'},{t:'ODC',r:'+',n:''},{t:'Sucrose',r:'+',n:''}],
  media:['CIN agar','MacConkey'],condition:'Cold enrichment (4°C); grows at 25°C',
  notes:'Motile at 25°C but non-motile at 37°C. Bull\'s eye colony on CIN agar. Causes pseudoappendicitis.'},
 {id:'salmonella_paratyphi_a',group:'enterobacterales',name:'Salmonella Paratyphi A',thai:'ซัลโมเนลลา พาราไทฟิ เอ',gram:'−',morph:'Rods',
  importance:'high',tags:['K/AG','H₂S−','LDC−','Paratyphoid'],
  clinical:{habitat:'Humans',diseases:['Paratyphoid fever'],transmission:'Fecal-oral',factors:'Capsule'},
  colony:{BAP:'Grey',MAC:'NLF',XLD:'Pink/red (NO black center)'},
  gramStain:'GNB',
  biochem:[{t:'TSI',r:'K/AG',n:'H₂S negative!'},{t:'H₂S',r:'−',n:'KEY exception to Salmonella'},{t:'Indole',r:'−',n:''},{t:'LDC',r:'−',n:'KEY exception'},{t:'Motility',r:'+',n:''}],
  media:['MacConkey','XLD'],condition:'37°C',
  notes:'Atypical Salmonella: H₂S negative and LDC negative.'},
 {id:'salmonella_arizonae',group:'enterobacterales',name:'Salmonella arizonae',thai:'ซัลโมเนลลา อาริโซเน',gram:'−',morph:'Rods',
  importance:'low',tags:['Reptiles','LD/OD+','Malonate+'],
  clinical:{habitat:'Reptiles, snakes',diseases:['Gastroenteritis'],transmission:'Contact with reptiles',factors:'Normal Salmonella factors'},
  colony:{BAP:'Grey',MAC:'NLF or LF'},
  gramStain:'GNB',
  biochem:[{t:'TSI',r:'A/AG H₂S',n:'May ferment lactose'},{t:'Malonate',r:'+',n:'KEY vs typical Salmonella'},{t:'ODC',r:'+',n:''},{t:'LDC',r:'+',n:''}],
  media:['MacConkey'],condition:'37°C',
  notes:'Malonate positive Salmonella.'},
 {id:'shigella_dysenteriae',group:'enterobacterales',name:'Shigella dysenteriae',thai:'ชิเกลลา ดิสเซนเทอรีเอ',gram:'−',morph:'Rods',
  importance:'high',tags:['Shiga toxin','Mannitol−','Serogroup A'],
  clinical:{habitat:'Humans',diseases:['Severe dysentery, HUS'],transmission:'Fecal-oral',factors:'Shiga toxin (exotoxin)'},
  colony:{BAP:'Grey',MAC:'NLF'},
  gramStain:'GNB',
  biochem:[{t:'TSI',r:'K/A',n:''},{t:'H₂S',r:'−',n:''},{t:'Motility',r:'−',n:''},{t:'Mannitol',r:'−',n:'KEY vs others (-/A/A/A)'},{t:'ODC',r:'−',n:''}],
  media:['MacConkey'],condition:'37°C',
  notes:'Serogroup A. Mannitol negative (others are +). Shiga toxin producer.'},
 {id:'shigella_flexneri',group:'enterobacterales',name:'Shigella flexneri',thai:'ชิเกลลา เฟลกซ์เนอรี',gram:'−',morph:'Rods',
  importance:'high',tags:['Serogroup B','Indole+/−','Mannitol+'],
  clinical:{habitat:'Humans',diseases:['Dysentery'],transmission:'Fecal-oral',factors:'Enterotoxins'},
  colony:{BAP:'Grey',MAC:'NLF'},
  gramStain:'GNB',
  biochem:[{t:'TSI',r:'K/A',n:''},{t:'H₂S',r:'−',n:''},{t:'Motility',r:'−',n:''},{t:'Indole',r:'V',n:''},{t:'Mannitol',r:'+',n:''}],
  media:['MacConkey'],condition:'37°C',
  notes:'Serogroup B.'},

 // VIBRIO
 {id:'vibrio_vulnificus',group:'vibrio',name:'Vibrio vulnificus',thai:'วิบริโอ วัลนิฟิคัส',gram:'−',morph:'Curved rods',
  importance:'critical',tags:['Necrotizing fasciitis','Liver disease','TCBS green','Lactose+'],
  clinical:{habitat:'Marine environments, oysters',diseases:['Primary septicemia (from consuming raw oysters, esp. in liver disease)','Severe necrotizing fasciitis'],transmission:'Raw seafood, seawater wound',factors:'Capsule, cytolysins, iron dependence'},
  colony:{BAP:'β-hemolysis',TCBS:'Green (85%) or Yellow (15%)'},
  gramStain:'GN curved rods',
  biochem:[{t:'Oxidase',r:'+',n:''},{t:'TCBS',r:'Green/Blue',n:''},{t:'0% NaCl',r:'−',n:'Requires salt'},{t:'1% NaCl',r:'+',n:''},{t:'Lactose',r:'+',n:'KEY: Only Vibrio that ferments lactose!'},{t:'Salicin',r:'+',n:''},{t:'LDC',r:'+',n:''}],
  media:['TCBS'],condition:'37°C',
  notes:'Extremely high mortality in liver disease patients. Key biochem: Lactose positive!'},
 {id:'vibrio_fluvialis',group:'vibrio',name:'Vibrio fluvialis',thai:'วิบริโอ ฟลูวิเอลิส',gram:'−',morph:'Curved rods',
  importance:'low',tags:['TCBS yellow','Arginine+'],
  clinical:{habitat:'Coastal environments',diseases:['Gastroenteritis'],transmission:'Seafood',factors:'Toxins'},
  colony:{TCBS:'Yellow'},
  gramStain:'GN curved rods',
  biochem:[{t:'TCBS',r:'Yellow',n:''},{t:'0% NaCl',r:'−',n:''},{t:'1% NaCl',r:'+',n:''},{t:'ADC (Arginine)',r:'+',n:''},{t:'Gas from Glucose',r:'−',n:''}],
  media:['TCBS'],condition:'37°C',
  notes:'Sucrose + like V. cholerae, but AD +.'},
 {id:'vibrio_alginolyticus',group:'vibrio',name:'Vibrio alginolyticus',thai:'วิบริโอ อัลจิโนลิติคัส',gram:'−',morph:'Curved rods',
  importance:'low',tags:['10%NaCl+','Wounds'],
  clinical:{habitat:'Seawater',diseases:['Otitis media, wound infection'],transmission:'Seawater contact',factors:'Halotolerant'},
  colony:{TCBS:'Yellow'},
  gramStain:'GN curved',
  biochem:[{t:'TCBS',r:'Yellow',n:''},{t:'0% NaCl',r:'−',n:''},{t:'6% NaCl',r:'+',n:''},{t:'8% NaCl',r:'+',n:'KEY'},{t:'VP (1% NaCl)',r:'+',n:''}],
  media:['TCBS'],condition:'37°C',
  notes:'Highly halophilic, grows in 8-10% NaCl.'},
 {id:'vibrio_mimicus',group:'vibrio',name:'Vibrio mimicus',thai:'วิบริโอ มิมิคัส',gram:'−',morph:'Curved rods',
  importance:'low',tags:['Mimics cholera','TCBS green'],
  clinical:{habitat:'Aquatic',diseases:['Gastroenteritis'],transmission:'Seafood',factors:'Cholera-like toxin'},
  colony:{TCBS:'Green/Blue'},
  gramStain:'GN curved',
  biochem:[{t:'TCBS',r:'Green/Blue',n:''},{t:'0% NaCl',r:'+',n:'Grows in 0% NaCl!'},{t:'VP (1% NaCl)',r:'−',n:''}],
  media:['TCBS'],condition:'37°C',
  notes:'Basically V. cholerae that is Sucrose negative.'},
 {id:'aeromonas_caviae',group:'vibrio',name:'Aeromonas caviae',thai:'แอโรโมแนส คาเวีย',gram:'−',morph:'Rods',
  importance:'moderate',tags:['Oxidase+','Freshwater','VP−','Arabinose+'],
  clinical:{habitat:'Freshwater',diseases:['Gastroenteritis (especially children)'],transmission:'Freshwater ingestion',factors:'Enterotoxins'},
  colony:{BAP:'Grey, often NON-hemolytic',MAC:'LF or NLF'},
  gramStain:'GNB',
  biochem:[{t:'Oxidase',r:'+',n:''},{t:'TCBS',r:'No growth',n:''},{t:'VP',r:'−',n:'KEY vs A. hydrophila (+)'},{t:'Arabinose',r:'+',n:''},{t:'0% NaCl',r:'+',n:''},{t:'6% NaCl',r:'−',n:''}],
  media:['Blood agar','MacConkey'],condition:'37°C',
  notes:'VP negative separates it from A. hydrophila/sobria. Often non-hemolytic.'},
 {id:'aeromonas_sobria',group:'vibrio',name:'Aeromonas sobria',thai:'แอโรโมแนส โซเบรีย',gram:'−',morph:'Rods',
  importance:'moderate',tags:['Oxidase+','Arabinose−'],
  clinical:{habitat:'Freshwater',diseases:['Gastroenteritis, bacteremia'],transmission:'Freshwater',factors:'Toxins'},
  colony:{BAP:'Beta-hemolytic'},
  gramStain:'GNB',
  biochem:[{t:'Oxidase',r:'+',n:''},{t:'VP',r:'+',n:''},{t:'Arabinose',r:'−',n:'KEY'},{t:'Esculin',r:'−',n:''}],
  media:['Blood agar'],condition:'37°C',
  notes:'Arabinose negative compared to A. hydrophila.'},

 // GNC (Neisseria)
 {id:'moraxella_catarrhalis',group:'gn_coccobacilli',name:'Moraxella catarrhalis',thai:'มอแรกเซลลา แคทาร์ราลิส',gram:'−',morph:'Diplococci',
  importance:'high',tags:['Hockey puck','Asaccharolytic','DNase+','Otitis media'],
  clinical:{habitat:'Upper respiratory tract',diseases:['Otitis media','Sinusitis','COPD exacerbations'],transmission:'Respiratory droplets',factors:'Beta-lactamase producer (>90%)'},
  colony:{ChocAgar:'Grey-pink, "hockey puck" sign (can be pushed intact across agar)'},
  gramStain:'GN diplococci (kidney bean)',
  biochem:[{t:'Oxidase',r:'+',n:''},{t:'CTA Glucose',r:'−',n:'KEY: Asaccharolytic!'},{t:'CTA Maltose',r:'−',n:''},{t:'CTA Lactose',r:'−',n:''},{t:'CTA Sucrose',r:'−',n:''},{t:'DNase',r:'+',n:'KEY: M. catarrhalis is DNase positive!'},{t:'Growth on Nutrient agar',r:'+',n:''},{t:'Nitrate reduction',r:'+',n:''}],
  media:['Chocolate agar','Blood agar'],condition:'37°C',
  notes:'Asaccharolytic (all CTA sugars negative). DNase positive is the key ID test. Hockey puck sign.'},
 {id:'neisseria_lactamica',group:'gn_coccobacilli',name:'Neisseria lactamica',thai:'ไนซีเรีย แลคทามิกา',gram:'−',morph:'Diplococci',
  importance:'low',tags:['CTA Lac+','Commensal'],
  clinical:{habitat:'Oral flora',diseases:['Rarely pathogenic'],transmission:'Respiratory',factors:'None'},
  colony:{ChocAgar:'Small grey'},
  gramStain:'GN diplococci',
  biochem:[{t:'Oxidase',r:'+',n:''},{t:'CTA Glucose',r:'+',n:''},{t:'CTA Maltose',r:'+',n:''},{t:'CTA Lactose',r:'+',n:'KEY'},{t:'CTA Sucrose',r:'−',n:''}],
  media:['Chocolate agar'],condition:'37°C',
  notes:'Ferments lactose. Typically non-pathogenic oral flora.'},
 {id:'neisseria_sicca',group:'gn_coccobacilli',name:'Neisseria sicca',thai:'ไนซีเรีย ซิคกา',gram:'−',morph:'Diplococci',
  importance:'low',tags:['CTA Suc+','Dry colony'],
  clinical:{habitat:'Oral flora',diseases:['Rarely pathogenic'],transmission:'Respiratory',factors:'None'},
  colony:{ChocAgar:'Dry, wrinkled, adherent'},
  gramStain:'GN diplococci',
  biochem:[{t:'Oxidase',r:'+',n:''},{t:'CTA Glucose',r:'+',n:''},{t:'CTA Maltose',r:'+',n:''},{t:'CTA Lactose',r:'−',n:''},{t:'CTA Sucrose',r:'+',n:'KEY'},{t:'Growth on Nutrient agar',r:'+',n:''}],
  media:['Nutrient agar'],condition:'37°C',
  notes:'Ferments sucrose. Grows on nutrient agar (vs fastidious pathogens).'},
 {id:'neisseria_mucosa',group:'gn_coccobacilli',name:'Neisseria mucosa',thai:'ไนซีเรีย มิวโคซา',gram:'−',morph:'Diplococci',
  importance:'low',tags:['Mucoid','Nitrate+'],
  clinical:{habitat:'Oral flora',diseases:['Endocarditis (rare)'],transmission:'Respiratory',factors:'Capsule'},
  colony:{ChocAgar:'Large, mucoid'},
  gramStain:'GN diplococci',
  biochem:[{t:'Oxidase',r:'+',n:''},{t:'CTA Glucose',r:'+',n:''},{t:'CTA Maltose',r:'+',n:''},{t:'CTA Lactose',r:'−',n:''},{t:'CTA Sucrose',r:'+',n:''},{t:'Nitrate reduction',r:'+',n:'KEY vs N. sicca (−)'}],
  media:['Chocolate agar'],condition:'37°C',
  notes:'Mucoid colonies. Nitrate positive.'}
];

const injectPoint = '// Merge LIBRARY arrays';

